apiVersion: v1		
kind: PersistentVolume		
metadata:		
  name: ita-by-sync		
  annotations:		
    volume.beta.kubernetes.io/storage-class: "slow"		
spec:		
  capacity:		
    storage: 1Gi		
  accessModes:		
    - ReadWriteOnce		
  persistentVolumeReclaimPolicy: Retain		
  nfs:		
   server: 10.197.19.188		
   path: /ky/share/ita2test/sync		

