openapi: 3.0.3
info:
  description: ITAv2.0 admin用API
  version: 1.0.0
  title: ITA Version2.0 admin API
tags:

  - name: Organization Create
    description: Organization作成
  - name: Workspace Create
    description: Workspace作成
paths:
  /api/organizations/{organization_id}/ita/:
    post:
      tags:
        - Organization Create
      description: Organizationを作成する
      operationId: organizationCreate
      parameters:
        - name: organization_id
          in: path
          description: OrganizationID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
    delete:
      tags:
        - Organization Create
      description: Organizationを削除する
      operationId: organizationDelete
      parameters:
        - name: organization_id
          in: path
          description: OrganizationID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'

  /api/{organization_id}/workspaces/{workspace_id}/ita/:
    post:
      tags:
        - Workspace Create
      description: Workspaceを作成する
      operationId: workspaceCreate
      parameters:
        - name: organization_id
          in: path
          description: organizationID
          required: true
          schema:
            type: string
        - name: workspace_id
          in: path
          description: WorkspaceID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              description: ロールID情報
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
    delete:
      tags:
        - Workspace Create
      description: Workspaceを削除する
      operationId: workspaceDelete
      parameters:
        - name: organization_id
          in: path
          description: organizationID
          required: true
          schema:
            type: string
        - name: workspace_id
          in: path
          description: WorkspaceID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'

components:
  schemas:
    ERROR_TEMPLATE:
      type: object
      properties:
        result:
          type: string
          example: 001-002
        message:
          type: string
