apiVersion: v1		
kind: PersistentVolume		
metadata:		
  name: ita-pv
  annotations:		
    volume.beta.kubernetes.io/storage-class: "slow"		
spec:		
  capacity:		
    storage: 10Gi		
  accessModes:		
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain		
  nfs:		
   server: 10.197.19.188		
   path: /ky/share/karino/ita-general

