apiVersion: v1		
kind: PersistentVolumeClaim		
metadata:		
  name: ita-pvc
  namespace: exastro-it-automation		
  labels:		
    app: centos-pv-test		
  annotations:		
    "volume.beta.kubernetes.io/storage-class": "slow"		
spec:		
  accessModes:		
    - ReadWriteMany
  resources:		
    requests:		
      storage: 10Gi		
  volumeName: ita-pv

