global:
  dbAccountInfo: secret-ita-mariadb
  dbConnectionInfo: params-ita-mariadb
  itaBaseInfo: params-ita-common
  itaByMenuCreateInfo: params-ita-by-menu-create
  itaApiOrg:  params-ita-org
  gitLabAccountInfo: secret-ita-gitlab
  gitLabConnectionInfo: params-ita-gitlab
  claimName: ita-pvc

# Default values for ita-by-menu-create.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
name: ita-api-admin
replicaCount: 1

extraenv:
  EXECUTE_INTERVAL: "1"
  STORAGEPATH: /storage/
  DEFAULT_LANGUAGE: ja
  LISTEN_PORT: 8080
  
initContainerCommand: 
  shell: sh
  option: -c
  arg: "chown -R 1000:1000 /storage "

initContainerVolume:
  mountPath:
    name: /storage
    
initContainerImage:
  repository: busybox
  pullPolicy: IfNotPresent #テスト環境用
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

image:
  repository: exastro/it-automation2-test-ita-api-admin
  pullPolicy: IfNotPresent #テスト環境用
  # Overrides the image tag whose default is the chart appVersion.
  tag: Integration-test.13dc22.20221004-213256
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# serviceAccount:
#   # Specifies whether a service account should be created
#   create: true
#   # Annotations to add to the service account
#   annotations: {}
#   # The name of the service account to use.
#   # If not set and create is true, a name is generated using the fullname template
#   name: ""


volume:
  mountPath:
    name1: /storage
    subPath1: httpd-pid
    subPath2: httpd-socket
    name2: /var/run_app_user/httpd/pid
    name3: /tmp
    name4: /home/app_user
    name5: /var/run_app_user/httpd/socket

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000


securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true

service:
  type: NodePort
  portsName: tomcat
  portsNumber: 8080
  portsTargetNumber: 8080

resources:
  requests:
    memory: "64Mi"  #仮決め
    cpu: "250m"     #仮決め
  limits:
    memory: "64Mi"  #仮決め
    cpu: "250m"     #仮決め

# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80
#   # targetMemoryUtilizationPercentage: 80

# nodeSelector: {}

# tolerations: []

# affinity: {}
