apiVersion: v1
appVersion: "1.0"
description: Web-based Git-repository manager with wiki and issue-tracking features.
maintainers:
- email: yoshifumi.karino@ncontr.com
  name: ykarino
name: ita2-test-helm
version: 0.1.0
