service:
  type: ClusterIP
  annotations: ""

persistence:
  ita-app:
    enabled: true
    accessMode: ReadWriteOnce
    size: 10Gi
    reclaimPolicy: Delete
  mariadb:
    enabled: true
    accessMode: ReadWriteOnce
    size: 10Gi
    reclaimPolicy: Delete
  organization-aaaa:
    enabled: true
    accessMode: ReadWriteOnce
    size: 10Gi
    reclaimPolicy: Delete

config:
  cluster_domain: cluster.local
  cluster_name: cassandra
  cluster_size: 3
  seed_size: 2
  num_tokens: 256
  # If you want Cassandra to use this datacenter and rack name,
  # you need to set endpoint_snitch to GossipingPropertyFileSnitch.
  # Otherwise, these values are ignored and datacenter1 and rack1
  # are used.
  dc_name: DC1
  rack_name: RAC1
  endpoint_snitch: SimpleSnitch
  max_heap_size: 2048M
  heap_new_size: 512M
  start_rpc: false
  ports:
    cql: 9042
    thrift: 9160
    # If a JVM Agent is in place
    # agent: 61621
  
securityContext:
  enabled: false
  fsGroup: 999
  runAsUser: 999