kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ita-azurefile
#provisioner: kubernetes.io/azure-file
provisioner: file.csi.azure.com
allowVolumeExpansion: true
reclaimPolicy: Retain
mountOptions:
  - dir_mode=0755
  - file_mode=0755
  - uid=0
  - gid=0
  - mfsymlinks
  - nobrl
  - noperm
parameters:
  skuName: Standard_LRS
  #skuName: Premium_LRS
