kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ita-pvc
  namespace: exastro-it-automation
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 12Gi
  storageClassName: azurefile-csi
