apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ita-mariadb
  namespace: exastro-it-automation
  labels:
    app: centos-pv-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  #storageClassName: azurefile-csi
  storageClassName: ita-azurefile
  #   volumeName: ita-mariadb
