version: '3.1'
services:
  ita-api-organization:
    build:
      dockerfile: ./ita_root/ita_api_organization/Dockerfile
      context: ../.
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - http_proxy=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - https_proxy=${HTTPS_PROXY}
    environment:
      - LISTEN_PORT=8000
      - PYTHONPATH=/exastro/
      - DB_HOST=ita-mariadb
      - DB_PORT=3306
      - DB_DATADBASE=ITA_DB
      - DB_USER=ITA_USER
      - DB_PASSWORD=password
      - DB_ROOT_PASSWORD=password
  ita-web-server:
    build:
      dockerfile: ./ita_root/ita_web_server/Dockerfile
      context: ../.
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - http_proxy=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - https_proxy=${HTTPS_PROXY}
    environment:
      - LISTEN_PORT=80
    ports:
      - "0.0.0.0:80:80"
  ita-mariadb:
    build:
      dockerfile: ./ita_root/ita_mariadb/Dockerfile
      context: ../.
    volumes:
      - ../.volumes/ita-mariadb/data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=ITA_DB
      - MARIADB_USER=ITA_USER
      - MARIADB_PASSWORD=password
