version: '3.1'
services:
  ita-api-organization:
    build:
      target: develop_build
    user: 1000:1000
    command: "python3 -m debugpy --listen 5678 /exastro/api.py"
    volumes:
      - ..:/workspace:cached
      - ../ita_root/common_libs:/workspace/ita_root/ita_api_organization/common_libs:cached
      - ../ita_root/messages:/workspace/ita_root/ita_api_organization/messages:cached
      - ../ita_root/ita_api_organization:/exastro:cached
      - ../ita_root/common_libs:/exastro/common_libs:cached
      - ../ita_root/messages:/exastro/messages:cached
      - ../ita_root/ita_api_organization/config/httpd.conf/httpd.conf:/etc/httpd/conf/httpd.conf:cached
      - ../ita_root/ita_api_organization/config/httpd.conf/wsgi.conf:/etc/httpd/conf.d/wsgi.conf:cached
      - ~/.netrc:/home/app_user/.netrc
      - ~/.gitconfig:/home/app_user/.gitconfig
      - ./ita-api-organization/.vscode/launch.json:/workspace/.vscode/launch.json
      - /usr/share/pki/ca-trust-source/anchors/UserRootCertificate.crt:/etc/ssl/certs/ca-certificates.crt
      - /mnt/mainte/talisman/.talismanrc:/mnt/mainte/talisman/.talismanrc
      - ~/.config/git/ignore:/home/app_user/.config/git/ignore
      - ${TALISMAN_HOME}:${TALISMAN_HOME}
    environment:
      - FLASK_ENV=development
      - HTTP_PROXY=${HTTP_PROXY}
      - http_proxy=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - https_proxy=${HTTPS_PROXY}
      - NO_PROXY=localhost,127.0.0.1,ita-api-organization,ita-web-server
      - no_proxy=localhost,127.0.0.1,ita-api-organization,ita-web-server
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
      - SSL_CERT_DIR=/etc/ssl/certs
      - NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
  ita-web-server:
    volumes:
      - ../ita_root/ita_web_server/contents/:/var/www/html/:cached
      - ../ita_root/ita_web_server/config/httpd.conf/httpd.conf:/etc/httpd/conf/httpd.conf:cached

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - ita-mariadb
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=ita-mariadb
    ports:
      - "8080:80"
    volumes:
      - ../.volumes/phpmyadmin/sessions:/sessions
