apiVersion: v1
kind: Service
metadata:
  name: ita-mariadb 
spec:
  type: ClusterIP
  ports:
    - name: mariadb 
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: mariadb 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ita-mariadb
  labels:
    app: mariadb # service will look for this label
  namespace: exastro-it-automation
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template: 
    metadata:
      labels:
        app: mariadb # service will look for this label
    spec: # specification for pods
      containers: # we can have one or more containers
      - name: mariadb
        image: ita-mariadb:0.4 
        ports:
        - containerPort: 3306 
        env:
          - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
            value: "0" # if it is 1 and root_password is set, root_password takes precedance
          - name: MARIADB_ROOT_PASSWORD
            value: password 
          - name: MARIADB_USER
            value: ITA_USER 
          - name: MARIADB_PASSWORD
            value: password 
          - name: MARIADB_DATABASE
            value: ITA_DB 
        securityContext:
          allowPrivilegeEscalation: true
          capabilities: {}
          privileged: true
          readOnlyRootFilesystem: false
          seLinuxOptions: {}
        volumeMounts:
          - name: persistent-storage
            # mountPath: /tmp
            mountPath: /var/lib/mysql
          - name: mysql-server-initdb
            mountPath: /docker-entrypoint-initdb.d
          - name: mysql-server-conf
            mountPath: /etc/mysql/conf.d
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: ita-mariadb 
      - name: mysql-server-initdb
        configMap:
          name: mysql-server-initdb-config
      - name: mysql-server-conf
        configMap:
          name: mysql-server-conf-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-server-initdb-config
  namespace: exastro-it-automation
data:
  createdb.sql: |
    CREATE DATABASE IF NOT EXISTS ITA_DB; 
    CREATE TABLE IF NOT EXISTS `ITA_DB`.`T_COMN_ORGANIZATION_DB_INFO`
    (
        PRIMARY_KEY                     VARCHAR(40),                                -- 主キー
        ORGANIZATION_ID                 VARCHAR(255),                               -- organizationのID
        DB_HOST                         VARCHAR(255),                               -- DBホスト
        DB_PORT                         INT,                                        -- DBポート
        DB_DATADBASE                    VARCHAR(255),                               -- DBDB名
        DB_USER                         VARCHAR(255),                               -- DBユーザ
        DB_PASSWORD                     VARCHAR(255),                               -- DBパスワード
        DB_ROOT_PASSWORD                VARCHAR(255),                               -- DBRootパスワード
        GITLAB_USER                     VARCHAR(255),                               -- GitLabユーザ
        GITLAB_TOKEN                    VARCHAR(255),                               -- GitLabトークン
        NOTE                            TEXT,                                       -- 備考
        DISUSE_FLAG                     VARCHAR(1)  ,                               -- 廃止フラグ
        LAST_UPDATE_TIMESTAMP           DATETIME(6),                                -- 最終更新日時
        LAST_UPDATE_USER                VARCHAR(40),                                -- 最終更新者
        PRIMARY KEY(PRIMARY_KEY)
    )ENGINE = InnoDB, CHARSET = utf8mb4, COLLATE = utf8mb4_bin, ROW_FORMAT=COMPRESSED ,KEY_BLOCK_SIZE=8;
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-server-conf-config
  namespace: exastro-it-automation
data:
  custom.cnf: |
    [mysqld]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: params-ita-maria
  namespace: exastro-it-automation
data:
  DB_HOST: "ita-mariadb"
  DB_PORT: "3306"
  DB_DATADBASE: "ITA_DB"
  DB_USER: "ITA_USER"
  STORAGEPATH: "/storage/"
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-ita-maria
  namespace: exastro-it-automation
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ=
  DB_ROOT_PASSWORD: cGFzc3dvcmQ=

