apiVersion: v1
kind: Secret
metadata:
  name: secret-ita-api-admin
  namespace: exastro-it-automation
type: Opaque
data:
  STEST: bXpzUWo4VlVfemNTb1Nac1NYX18= #temporary one
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: params-ita-admin
  namespace: exastro-it-automation
data:
  TEST: "hello"  # temporary one
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ita-api-admin
  namespace: exastro-it-automation 
spec:
  selector:
    matchLabels:
      name: ita-api-admin 
  replicas: 1 
  template:
    metadata:
      labels:
        name: ita-api-admin 
    spec:
      containers:
      - name: ita-api-admin 
        image: ita-api-admin:0.4 
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: secret-ita-maria
            name: secret-ita-common
        - configMapRef:
            name: params-ita-maria 
            name: params-ita-common 
        #volumeMounts:   
        #  - name: persistent-storage
        #    mountPath: /hoge # <--- Please activate this block after correct path to mount is fixed
      #volumes:
      #- name: persistent-storage
      #  persistentVolumeClaim:
      #    claimName: ita-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ita-api-admin 
  namespace: exastro-it-automation 
  labels:
    name: ita-api-admin 
spec:
  type: NodePort 
  ports:
  - name: tomcat
    port: 8080
    targetPort: 8080
  selector:
    name: ita-api-admin 
