openapi: 3.0.3
info:
  title: ITA Version2.0 API
  description: ITAv2.0用API
  version: 1.0.0
servers:
- url: /
tags:
- name: Workspace Create
  description: ワークスペース作成
- name: Menu Info
  description: メニュー情報の取得
- name: Menu Filter
  description: レコードの取得
- name: Menu Maintenance
  description: レコードの操作（登録/更新/廃止/復活/物理削除）
- name: Menu MaintenanceAll
  description: レコードの一括操作（登録/更新/廃止/復活/物理削除）
paths:
  /api/workspaces/{workspace_id}/:
    get:
      tags:
      - Workspace Create
      description: ワークスペースを作成する
      operationId: workspace_create
      parameters:
      - name: workspace_id
        in: path
        description: ワークスペース名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                properties: {}
                items:
                  type: string
                x-content-type: application/json
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      x-openapi-router-controller: controllers.workspace_create_controller
  /api/menu/{workspace}/{menu}/info/:
    get:
      tags:
      - Menu Info
      description: メニューの基本情報および項目情報を取得する
      operationId: get_info
      parameters:
      - name: workspace
        in: path
        description: ワークスペース名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: menu
        in: path
        description: メニュー名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                properties:
                  COLUMN_INFO:
                    $ref: '#/components/schemas/COLUMN_INFO'
                  BASIC_INFO:
                    $ref: '#/components/schemas/BASIC_INFO'
                items:
                  type: string
                x-content-type: application/json
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      x-openapi-router-controller: controllers.menu_info_controller
  /api/menu/{workspace}/{menu}/info/basic/:
    get:
      tags:
      - Menu Info
      description: メニューの基本情報を取得する
      operationId: get_basic_info
      parameters:
      - name: workspace
        in: path
        description: ワークスペース名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: menu
        in: path
        description: メニュー名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                properties:
                  BASIC_INFO:
                    $ref: '#/components/schemas/BASIC_INFO'
                items:
                  type: string
                x-content-type: application/json
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      x-openapi-router-controller: controllers.menu_info_controller
  /api/menu/{workspace}/{menu}/info/column/:
    get:
      tags:
      - Menu Info
      description: メニューの項目情報を取得する
      operationId: get_column_info
      parameters:
      - name: workspace
        in: path
        description: ワークスペース名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: menu
        in: path
        description: メニュー名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                properties:
                  COLUMN_INFO:
                    $ref: '#/components/schemas/COLUMN_INFO'
                items:
                  type: string
                x-content-type: application/json
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      x-openapi-router-controller: controllers.menu_info_controller
  /api/menu/{workspace}/{menu}/info/pulldown/{restname}/:
    get:
      tags:
      - Menu Info
      description: 項目のプルダウン選択用の一覧を取得する
      operationId: get_info_pulldown_list
      parameters:
      - name: workspace
        in: path
        description: ワークスペース名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: menu
        in: path
        description: メニュー名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: restname
        in: path
        description: REST用項目名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                properties: {}
                items:
                  type: string
                x-content-type: application/json
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      x-openapi-router-controller: controllers.menu_info_controller
  /api/menu/{workspace}/{menu}/filter/:
    get:
      tags:
      - Menu Filter
      description: レコードを全件取得する
      operationId: get_filter
      parameters:
      - name: workspace
        in: path
        description: ワークスペース名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: menu
        in: path
        description: メニュー名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      x-openapi-router-controller: controllers.menu_filter_controller
    post:
      tags:
      - Menu Filter
      description: 検索条件を指定し、レコードを取得する
      operationId: post_filter
      parameters:
      - name: workspace
        in: path
        description: ワークスペース名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: menu
        in: path
        description: メニュー名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: 検索条件を設定
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      x-openapi-router-controller: controllers.menu_filter_controller
  /api/menu/{workspace}/{menu}/maintenance/:
    post:
      tags:
      - Menu Maintenance
      description: レコードを登録する
      operationId: maintenance_register
      parameters:
      - name: workspace
        in: path
        description: ワークスペース名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: menu
        in: path
        description: メニュー名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: 登録する値を設定
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      x-openapi-router-controller: controllers.menu_maintenance_controller
  /api/menu/{workspace}/{menu}/maintenance/{uuid}:
    delete:
      tags:
      - Menu Maintenance
      description: レコードを物理削除
      operationId: maintenance_discard
      parameters:
      - name: workspace
        in: path
        description: ワークスペース名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: menu
        in: path
        description: メニュー名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: uuid
        in: path
        description: 対象のUUID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      x-openapi-router-controller: controllers.menu_maintenance_controller
    patch:
      tags:
      - Menu Maintenance
      description: レコードを更新/廃止/復活する
      operationId: maintenance_update
      parameters:
      - name: workspace
        in: path
        description: ワークスペース名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: menu
        in: path
        description: メニュー名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: uuid
        in: path
        description: 対象のUUID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: 更新する値を設定。廃止/復活は廃止フラグを更新することで実施。
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      x-openapi-router-controller: controllers.menu_maintenance_controller
  /api/menu/{workspace}/{menu}/maintenance/all/:
    post:
      tags:
      - Menu MaintenanceAll
      description: レコードを一括で登録/更新/廃止/復活する
      operationId: maintenance_all
      parameters:
      - name: workspace
        in: path
        description: ワークスペース名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: menu
        in: path
        description: メニュー名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: 登録/更新/廃止/復活するidとレコードの値を設定
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      x-openapi-router-controller: controllers.menu_maintenance_all_controller
components:
  schemas:
    TABLE:
      type: object
      properties:
        PAGE_NO:
          type: integer
        TD:
          type: object
        TD_IHP:
          type: object
        UNIQUE_VAL:
          type: object
      example:
        TD: {}
        TD_IHP: {}
        PAGE_NO: 0
        UNIQUE_VAL: {}
    COLUMN_INFO:
      type: object
      additionalProperties:
        type: object
        properties:
          column_id:
            type: string
            description: 項目ID
          column_name:
            type: string
            description: 表示用項目名
          column_name_rest:
            type: string
            description: REST用項目名
          column_group:
            type: string
            description: カラムグループ名
          column_type:
            type: integer
            description: カラムタイプ
          column_disp_seq:
            type: integer
            description: 表示順
          description:
            type: string
            description: 項目説明
          ref_table_name:
            type: string
            description: ID連携テーブル名
          ref_pkey_name:
            type: string
            description: ID連携テーブルPK
          ref_col_name:
            type: string
            description: ID連携項目名
          ref_sort_conditions:
            type: string
            description: ID連携ソート条件
          ref_multi_lang:
            type: string
            description: ID連携多言語対応有無
          col_name:
            type: string
            description: データベース上のカラム名
          save_type:
            type: string
            description: データベース上の保存形式
          auto_input:
            type: integer
            description: 自動入力フラグ
          input_item:
            type: integer
            description: 入力対象フラグ
          view_item:
            type: string
            description: 出力対象フラグ
          unique_item:
            type: integer
            description: 必須入力フラグ
          required_item:
            type: integer
            description: 一意制約フラグ
          initial_value:
            type: string
            description: 入力欄初期値
          validate_option:
            type: object
            description: バリデーション値
          before_validate_register:
            type: object
            description: 個別バリデーション(前)
          after_validate_register:
            type: object
            description: 個別バリデーション(後)
          filter_type:
            type: object
            description: 検索タイプ
          pulldown_info:
            type: object
            description: プルダウン選択情報
      description: column_name_restがkeyになる
    BASIC_INFO:
      type: object
      properties:
        menu_info:
          type: string
          description: メニューの説明
        menu_name:
          type: string
          description: メニューの名称
        sheet_type:
          type: string
          description: メニューのシートタイプ
        table_name:
          type: string
          description: テーブル名
        view_name:
          type: string
          description: ビュー名
        inherit:
          type: boolean
          description: 継承フラグ
        vertical:
          type: boolean
          description: 縦型フラグ
        login_necessity:
          type: boolean
          description: 認証有無
        auto_filter_flg:
          type: boolean
          description: オートフィルタフラグ
        initial_filter_flg:
          type: boolean
          description: 初回フィルタフラグ
        web_print_limit:
          type: integer
          description: Web表示最大行数
        web_print_confirm:
          type: integer
          description: Web表示前確認行数
        xls_print_limit:
          type: integer
          description: Excel出力最大行数
        sort_key:
          type: string
          description: ソートキー
    inline_response_200:
      type: object
      properties:
        TABLE:
          $ref: '#/components/schemas/TABLE'
      example:
        TABLE:
          TD: {}
          TD_IHP: {}
          PAGE_NO: 0
          UNIQUE_VAL: {}
    inline_response_200_1:
      type: object
      properties:
        status:
          type: string
      example:
        status: status

